export type State = {
  name: string;
  capital: string;
  abbr: string;
  region: "northeast" | "midwest" | "south" | "west";
};

export const STATES: State[] = [
  { name: "Alabama", capital: "Montgomery", abbr: "AL", region: "south" },
  { name: "Alaska", capital: "Juneau", abbr: "AK", region: "west" },
  { name: "Arizona", capital: "Phoenix", abbr: "AZ", region: "west" },
  { name: "Arkansas", capital: "Little Rock", abbr: "AR", region: "south" },
  { name: "California", capital: "Sacramento", abbr: "CA", region: "west" },
  { name: "Colorado", capital: "Denver", abbr: "CO", region: "west" },
  { name: "Connecticut", capital: "Hartford", abbr: "CT", region: "northeast" },
  { name: "Delaware", capital: "Dover", abbr: "DE", region: "south" },
  { name: "Florida", capital: "Tallahassee", abbr: "FL", region: "south" },
  { name: "Georgia", capital: "Atlanta", abbr: "GA", region: "south" },
  { name: "Hawaii", capital: "Honolulu", abbr: "HI", region: "west" },
  { name: "Idaho", capital: "Boise", abbr: "ID", region: "west" },
  { name: "Illinois", capital: "Springfield", abbr: "IL", region: "midwest" },
  { name: "Indiana", capital: "Indianapolis", abbr: "IN", region: "midwest" },
  { name: "Iowa", capital: "Des Moines", abbr: "IA", region: "midwest" },
  { name: "Kansas", capital: "Topeka", abbr: "KS", region: "midwest" },
  { name: "Kentucky", capital: "Frankfort", abbr: "KY", region: "south" },
  { name: "Louisiana", capital: "Baton Rouge", abbr: "LA", region: "south" },
  { name: "Maine", capital: "Augusta", abbr: "ME", region: "northeast" },
  { name: "Maryland", capital: "Annapolis", abbr: "MD", region: "south" },
  { name: "Massachusetts", capital: "Boston", abbr: "MA", region: "northeast" },
  { name: "Michigan", capital: "Lansing", abbr: "MI", region: "midwest" },
  { name: "Minnesota", capital: "Saint Paul", abbr: "MN", region: "midwest" },
  { name: "Mississippi", capital: "Jackson", abbr: "MS", region: "south" },
  { name: "Missouri", capital: "Jefferson City", abbr: "MO", region: "midwest" },
  { name: "Montana", capital: "Helena", abbr: "MT", region: "west" },
  { name: "Nebraska", capital: "Lincoln", abbr: "NE", region: "midwest" },
  { name: "Nevada", capital: "Carson City", abbr: "NV", region: "west" },
  { name: "New Hampshire", capital: "Concord", abbr: "NH", region: "northeast" },
  { name: "New Jersey", capital: "Trenton", abbr: "NJ", region: "northeast" },
  { name: "New Mexico", capital: "Santa Fe", abbr: "NM", region: "west" },
  { name: "New York", capital: "Albany", abbr: "NY", region: "northeast" },
  { name: "North Carolina", capital: "Raleigh", abbr: "NC", region: "south" },
  { name: "North Dakota", capital: "Bismarck", abbr: "ND", region: "midwest" },
  { name: "Ohio", capital: "Columbus", abbr: "OH", region: "midwest" },
  { name: "Oklahoma", capital: "Oklahoma City", abbr: "OK", region: "south" },
  { name: "Oregon", capital: "Salem", abbr: "OR", region: "west" },
  { name: "Pennsylvania", capital: "Harrisburg", abbr: "PA", region: "northeast" },
  { name: "Rhode Island", capital: "Providence", abbr: "RI", region: "northeast" },
  { name: "South Carolina", capital: "Columbia", abbr: "SC", region: "south" },
  { name: "South Dakota", capital: "Pierre", abbr: "SD", region: "midwest" },
  { name: "Tennessee", capital: "Nashville", abbr: "TN", region: "south" },
  { name: "Texas", capital: "Austin", abbr: "TX", region: "south" },
  { name: "Utah", capital: "Salt Lake City", abbr: "UT", region: "west" },
  { name: "Vermont", capital: "Montpelier", abbr: "VT", region: "northeast" },
  { name: "Virginia", capital: "Richmond", abbr: "VA", region: "south" },
  { name: "Washington", capital: "Olympia", abbr: "WA", region: "west" },
  { name: "West Virginia", capital: "Charleston", abbr: "WV", region: "south" },
  { name: "Wisconsin", capital: "Madison", abbr: "WI", region: "midwest" },
  { name: "Wyoming", capital: "Cheyenne", abbr: "WY", region: "west" },
];
